"""create moon table

Revision ID: 6bbf937cad27
Revises: 4f36b8712995
Create Date: 2025-11-05 11:55:43.161564

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6bbf937cad27'
down_revision = '4f36b8712995'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('moon', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('moon', schema=None) as batch_op:
        batch_op.drop_column('name')

    # ### end Alembic commands ###
